### ISSUE TITLE
Angular 9 Support

### ISSUE THREAD

**Issue by Liioooo** [dockleryxk/ng-simple-slideshow#101]
Angular 9 will be released in the near future and I would like to continue using your package.
Would be nice if it was compatible with ng9.

**Comment by JustACodeMonkey** [comment]
Agreed. Just updated an app to Angular 9 and get ...
ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at SlideshowComponent.push../node_modules/ng-simple-slideshow/__ivy_ngcc__/ng-simple-slideshow.es5.js.SlideshowComponent.setStyles

**Comment by Liioooo** [comment]
That's just what I did in my PR #102.

**Comment by Hermholtz** [comment]
Please merge PR #102.

**Comment by dockleryxk** [comment]
Done, and available in beta.10
