### ISSUE TITLE
Auto play stops when I click right or left arrow buttons

### ISSUE THREAD

**Issue by mstrYoda** [dockleryxk/ng-simple-slideshow#12]
I add slideshow component to my component.html file as following:

` 
<slideshow [imageUrls]="imageSources" [autoPlay]="true" [height]="800"></slideshow>
`

I start website with:

`ng serve --open`

Issue:

In the first opening of web site the slideshow slides normally, when I click right arrow it slides next image but autoplay stops. I expect it to keep sliding.

**Comment by dockleryxk** [comment]
you need to use [stopAutoPlayOnSlide]="false"

**Comment by mstrYoda** [comment]
thank you, I should have looked more carefully to the readme 😀
