### ISSUE TITLE
background-image not set if the image path contains space

### ISSUE THREAD

**Issue by lazaroreyesjobsity** [dockleryxk/ng-simple-slideshow#14]
If the image path contains space the background-image property is not set, even if you encode the path before initializing the slideshow

**Comment by dockleryxk** [comment]
@lazaroreyesjobsity thanks for letting me know. I will see if I can work this out. In the meantime, do you have any suggestions for a fix?

**Comment by dockleryxk** [comment]
@lazaroreyesjobsity have you tried escaping? https://stackoverflow.com/questions/2405333/css-background-image-path-issues

**Comment by dockleryxk** [comment]
@lazaroreyesjobsity could you post the URL of the image that isn't working for you?

**Comment by dockleryxk** [comment]
I am closing this issue as I cannot recreate it and it's been inactive for over two weeks. If you can recreate it then I will be happy to reopen.

**Comment by lazaroreyesjobsity** [comment]
@dockleryxk Sorry I've been really busy, here you have an example:
https://gend4.com/api/Containers/images/download/images (1).jpg
If you use this url that contains space, background-image is omitted, just like:
`<div _ngcontent-c24="" class="slides selected slide-in-right" ng-reflect-ng-style="[object Object]" style="background-size: cover; background-position: center center; background-repeat: no-repeat;"></div>`

**Comment by dockleryxk** [comment]
Looks like it was actually the parentheses. This worked for me https://gend4.com/api/Containers/images/download/images%20%281%29.jpg

I would suggest using encodeURI() before inserting them into the component

**Comment by lazaroreyesjobsity** [comment]
@dockleryxk Replacing the parentheses solved all my problems :) Thank you!
