### ISSUE TITLE
Property 'goToSlide' does not exist on type 'ElementRef

### ISSUE THREAD

**Issue by enginmarshall** [dockleryxk/ng-simple-slideshow#17]
I get this error message when using the example from the API section on the NPM page:

ERROR in src/app/decision-ui/decision-ui.component.ts(51,20): error TS2339: Property 'goToSlide' does not exist on type 'ElementRef'.
src/app/decision-ui/decision-ui.component.ts(57,20): error TS2339: Property 'goToSlide' does not exist on type 'ElementRef'.

**Comment by dockleryxk** [comment]
try changing the the type 'ElementRef' to 'any.' If this is an issue I will change the readme

**Comment by enginmarshall** [comment]
It works when the type is changed to any, Thanks for quick answer. :)

**Comment by dockleryxk** [comment]
No problem, I have no life :')

I will close this once I update the readme

**Comment by madhuri03** [comment]
please use  @ViewChild('slideshow') slideshow: any;
this works me fine

**Comment by akashdell** [comment]
This line works for me
 @ViewChild('slideshow') slideshow: any;
