### ISSUE TITLE
no docs on how to add captions or change css

### ISSUE THREAD

**Issue by Christopher-Jakob** [dockleryxk/ng-simple-slideshow#18]
You show how to display captions or not, how to change their colors but you do not show how to add the text of captions or change their location within the slideshow please adjust docs to show thank you.

**Comment by dockleryxk** [comment]
Currently, there is no way to change the location of the captions. What is the placement you are looking for?
As far as the contents of the captions, you must pass in an array of type [IImage](https://github.com/dockleryxk/ng-simple-slideshow/blob/master/src/app/modules/slideshow/IImage.ts) which is linked from the docs, but it is only implied I suppose. I will make it more clear. Thank you for pointing this out.

**Comment by dockleryxk** [comment]
Whoops, didn't mean to close this!

**Comment by dockleryxk** [comment]
Okay, I am going to close this due to lack of response. However, feel free to respond still.
