### ISSUE TITLE
ERROR TypeError: Cannot set property 'selected' of undefined

### ISSUE THREAD

**Issue by winadiw** [dockleryxk/ng-simple-slideshow#19]
`ERROR TypeError: Cannot set property 'selected' of undefined
    at SlideshowComponent.buildSlideArray (ng-simple-slideshow.es5.js:325)
    at SlideshowComponent.setSlides (ng-simple-slideshow.es5.js:280)
    at SlideshowComponent.ngDoCheck (ng-simple-slideshow.es5.js:95)
    at checkAndUpdateDirectiveInline (core.js:12372)
    at checkAndUpdateNodeInline (core.js:13893)
    at checkAndUpdateNode (core.js:13836)
    at debugCheckAndUpdateNode (core.js:14729)
    at debugCheckDirectivesFn (core.js:14670)
    at Object.eval [as updateDirectives] (DetailProductsComponent.html:3)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14655)
View_DetailProductsComponent_0 @ DetailProductsComponent.html:3
proxyClass @ compiler.js:14653
DebugContext_.logError @ core.js:14996
ErrorHandler.handleError @ core.js:1509
(anonymous) @ core.js:5914
ZoneDelegate.invoke @ zone.js:388
Zone.run @ zone.js:138
NgZone.runOutsideAngular @ core.js:4697
ApplicationRef.tick @ core.js:5914
(anonymous) @ core.js:5740
ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4749
ZoneDelegate.invoke @ zone.js:387
Zone.run @ zone.js:138
NgZone.run @ core.js:4566
next @ core.js:5740
schedulerFn @ core.js:4331
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4311
checkStable @ core.js:4714
onHasTask @ core.js:4762
ZoneDelegate.hasTask @ zone.js:441
ZoneDelegate._updateTaskCount @ zone.js:461
Zone._updateTaskCount @ zone.js:285
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
ZoneDelegate.scheduleTask @ zone.js:410
Zone.scheduleTask @ zone.js:232
Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:856
ZoneAwarePromise.then @ zone.js:946
PlatformRef.bootstrapModule @ core.js:5568
(anonymous) @ main.ts:13
./src/main.ts @ main.bundle.js:613
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:621
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
`
i'm trying to use simple slideshow in Angular 5.2.9, CLI 1.7.3, Node 9.10.1 but got the error

**Comment by dockleryxk** [comment]
Can you post how you're using the <slideshow> tag and the ts code pertaining to it? Somehow there are no slides, so the only advice I can give you with what you have supplied is that you need to initialize your array of slides when declaring it.

**Comment by winadiw** [comment]
So in the `[imageUrls]` array the image url is obtain from API. So i guess the html is rendered first before all the image url is completely get from API. I fix it by initializing `imageUrlArray=['']`, an empty array.  
Anyhow, it seems that if not specify the height the slideshow will not show.

**Comment by dockleryxk** [comment]
try v1.1.9

**Comment by winadiw** [comment]
i see, thanks for the help @dockleryxk. Nice package btw, i use it because i need carousel/slideshow that support Universal.

**Comment by Vatsal-Innovatemr** [comment]
@dockleryxk: I am still seeing this error "**ERROR TypeError: Cannot set property 'selected' of undefined**"

**Comment by dockleryxk** [comment]
@Vatsal-Innovatemr what version?

**Comment by Vatsal-Innovatemr** [comment]
> @Vatsal-Innovatemr what version?

I am using version 1.2.8 as I update the version it works fine.
Thanks for your response.
