### ISSUE TITLE
css overrides

### ISSUE THREAD

**Issue by BrownEli** [dockleryxk/ng-simple-slideshow#25]
Is there a wat to override width height ans background-size via css?

**Comment by dockleryxk** [comment]
I'm not entirely sure, but this is what I would try:

```typescript
<slideshow [height]="null"
           [minHeight]="null"
           [backgroundSize]="null">
</slideshow>
```

Then, try to change these with css. Let me know if this works!

**Comment by dockleryxk** [comment]
Another thing about width: I designed the slideshow to fill the width of its container, so you could just set the width of that in CSS.

I am going to close this issue, but still feel free to comment here.
