### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by MohitKS5** [dockleryxk/ng-simple-slideshow#3]
how to implement in angular 4? what to import in module.ts

**Comment by dockleryxk** [comment]
Did you figure this out?

**Comment by MohitKS5** [comment]
Got what to include in module.ts but still got an error so I had to shift to slick though I liked urs slider more

**Comment by dockleryxk** [comment]
Ah, I wish I knew what the error was. If you have time please provide that error and I can investigate

**Comment by dockleryxk** [comment]
by the way, I have updated the documentation in case that helps
