### ISSUE TITLE
Nice doc

### ISSUE THREAD

**Issue by TeodorKolev** [dockleryxk/ng-simple-slideshow#30]
`@ViewChild() slideshow: any;`

nice!

**Comment by dockleryxk** [comment]
you don't like this???

**Comment by TeodorKolev** [comment]
I should like something that is not working?

**Comment by dockleryxk** [comment]
Ah, I took that as sarcasm since there is no typing. I don't exactly know how to make a typing for the component ElementRef, but I think it works just fine like this.

Glad you like it!

**Comment by TeodorKolev** [comment]
No, it's not.

**Comment by TeodorKolev** [comment]
Besides that plugin is great. I put a star on it

**Comment by dockleryxk** [comment]
thanks!
