### ISSUE TITLE
Positioning the caption

### ISSUE THREAD

**Issue by fayeeg** [dockleryxk/ng-simple-slideshow#35]
Hi,

Could you please advise how do I position the caption in the center of the slide?

regards,
Fayeeg

**Comment by dockleryxk** [comment]
Using css you can target its class ```.caption```

**Comment by ChocolateAceCream** [comment]
> Using css you can target its class `.caption`

Hi. I'm trying to locate caption in the center but not able to do so using css class .caption to target it. Could you give me some suggestions please?

**Comment by ChocolateAceCream** [comment]
> Using css you can target its class `.caption`

actually I'm not able to target with .caption, I have to hard-code the slideshow element like this:

style="text-align: center"
