### ISSUE TITLE
how to add local image urls

### ISSUE THREAD

**Issue by ameydeshpande18** [dockleryxk/ng-simple-slideshow#37]
I tried to add the local image urls but seems it not working. Is it required to use the hosted image urls and not the images inside the application images folder?

**Comment by dockleryxk** [comment]
please send an example of the code, it should work just fine with local images

**Comment by dockleryxk** [comment]
see how [here](https://github.com/dockleryxk/ng-simple-slideshow/blob/master/src/app/app.component.ts#L14)
