### ISSUE TITLE
Extend peer dependencies to Angular 7

### ISSUE THREAD

**Issue by jaysaikia** [dockleryxk/ng-simple-slideshow#46]
`npm WARN @agm/core@1.0.0-beta.5 requires a peer of @angular/common@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.`
`npm WARN @agm/core@1.0.0-beta.5 requires a peer of @angular/core@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by dockleryxk** [comment]
Oh man, it's already time for the next version! If you notice any issues, let me know. I'll get this updated.

**Comment by dockleryxk** [comment]
@jaysaikia wait....I do need to do this but I think you have the wrong repo

**Comment by jaysaikia** [comment]
@dockleryxk nope ... I think this is the right one. I will check anyway.

**Comment by jaysaikia** [comment]
I pasted the wrong warn message. Lol.
I was about to put the request at agm too.
