### ISSUE TITLE
Pause button for the slideshow

### ISSUE THREAD

**Issue by ItamarSerafim** [dockleryxk/ng-simple-slideshow#48]
I couldn't find a way to pause the slideshow. Is this feature missing?

**Comment by dockleryxk** [comment]
@ItamarSerafim do you mean a play/pause button, or just to pause at any point?

**Comment by ItamarSerafim** [comment]
Yes, that's it: Play/Pause button, sou that I could paused the slideshow at any slide.
I notice that when I click previous button, the slider seems to pause the slideshow, but it seems not to be intuitive for the user.

**Comment by dockleryxk** [comment]
The behavior you have reference is due to the `stopAutoPlayOnSlide` option. 

While I don't currently plan on the feature, I will leave this open. I might add one in the future. I am also open to PRs.

**Comment by darssen** [comment]
Hi, I am using the slideshow and also found that it would be useful to have that feature. Pausing is easy since you can set to false the autoPlay option. But enabling it later does not seem to have the expected result.
Not sure if PR will be difficult due to my angular "expertise", but want to give it a try if you can share some guidelines.

**Comment by darssen** [comment]
Well looks like I might have found it.

In the **handleAutoPlay** method when you **clearInterval** the interval is cleared, but the value of **this._autoplayIntervalId** never gets removed. Thus even if you set Autoplay again, the interval never gets reset. 
Adding a `this._autoplayIntervalId = null;` after clearing the interval seems to do the trick.
Testing in the demo application, clicking and unclicking the Autoplay checkbox works as expected.

I'll create a PR so you can review it.

**Comment by dockleryxk** [comment]
I'll be reviewing this tonight!
