### ISSUE TITLE
multiple autoPlayInterval values

### ISSUE THREAD

**Issue by steolits** [dockleryxk/ng-simple-slideshow#50]
Hi, is it possible to assign a different auto play intervals?
For instance:
img1 --> 3000
img2 --> 5000
img3 --> 5000
img4 --> 10000

thanks for your support!

**Comment by dockleryxk** [comment]
Currently, it is not possible, but I will look into adding this. Could be a good feature.

**Comment by steolits** [comment]
Thank you!

**Comment by dockleryxk** [comment]
I don't think this makes sense for this package to have this. However, you could manually trigger this if needed with your own timers.
