### ISSUE TITLE
refresh images

### ISSUE THREAD

**Issue by steolits** [dockleryxk/ng-simple-slideshow#51]
Hi, is it possible to reload the images every time the carousel starts up again?
Thank you!

**Comment by dockleryxk** [comment]
Hmm it should be detecting the changes and showing the new images. Is the source for the image the same? 
Also, thanks for the debugging!! I will try to get to the bottom of why that error is happening and likely implement that code.

**Comment by steolits** [comment]
Yes, the source is the same. I have a windows service that every time t overwrite the images with the newest versions.

**Comment by dockleryxk** [comment]
try adding a random query parameter at the end of the slide urls for this behavior. Ultimately, this is outside the scope of this package.
