### ISSUE TITLE
Zoom images

### ISSUE THREAD

**Issue by Palum12** [dockleryxk/ng-simple-slideshow#52]
Hi, is it possible to allow user to zoom images shown with this component ?

**Comment by dockleryxk** [comment]
Do you mean like a fullscreen type of functionality?

**Comment by Palum12** [comment]
No, more like Google Maps zoom. When using "contain" size option the full picture is shown to user. But user might want to use something like "+" button to zoom in / focus on details of picture.

**Comment by dockleryxk** [comment]
There isn't a way currently, but I'd be open to PRs. I'll leave this open for a while in case anyone else wants to chime in.

**Comment by jaysaikia** [comment]
Fullscreen would be a nice feature to have as well, Instead of loading a new slideshow in fullscreen.

**Comment by jaysaikia** [comment]
Is anyone taking this up ?
@dockleryxk "hammerjs" ?

**Comment by dockleryxk** [comment]
@jaysaikia I don't like the idea of relying on hammer, I was thinking about implementing something similar to [this](https://www.w3schools.com/howto/howto_js_image_zoom.asp), except the image will just zoom, not zoom in another box.

**Comment by jaysaikia** [comment]
@dockleryxk I have some time to work on this. If hammerjs is out, would you rather do a custom event capture to detect pinch in/out ? [link](https://github.com/mdn/dom-examples/blob/master/pointerevents/Pinch_zoom_gestures.html)

**Comment by dockleryxk** [comment]
@jaysaikia assuming that code works, I am open to that! If you make it work client side, I will angular-ize it and make it work for server-side! Unless you want to do that too.

A note on hammer: 

1. I have no inherent issue with hammer, but I like the fact that this package is lightweight, and I would like to keep it as lightweight as possible!
2. Hammerjs is tricky to get working with server-side. I don't want to subject people to that.

Thanks!

**Comment by jaysaikia** [comment]
@dockleryxk 
https://github.com/jaysaikia/ng-simple-slideshow/commit/3189c794ca01fd1372cd5a6509c0345ea6a65208#commitcomment-33419991

**Comment by dockleryxk** [comment]
This is available in 1.3.0-beta.0, thanks @jaysaikia !!!

**Comment by dockleryxk** [comment]
I am going to close this since it has been available
