### ISSUE TITLE
href target set to _blank

### ISSUE THREAD

**Issue by myv1nyl** [dockleryxk/ng-simple-slideshow#53]
Is it possible to tell the slideshow to open links in a new tab?

**Comment by dockleryxk** [comment]
Not currently but this will be simple to implement

**Comment by myv1nyl** [comment]
I've been meaning to post this. 

While this may not be the best solution, clickAction: () => window.open(href) works to get a new tab from clicking the slide. Feels a bit hacky, considering the element is an <a>, but it gets the job done.

**Comment by dockleryxk** [comment]
This should be fixed in v1.3.0-beta.0
