### ISSUE TITLE
New output events: Current slide index change event

### ISSUE THREAD

**Issue by jaysaikia** [dockleryxk/ng-simple-slideshow#55]
It would be great to have a slide index change event. This could also be used to check initialisation from no image to some images being shown.

The slideLeft and slideRight does not fire when image is newly added to an empty array.

**Comment by dockleryxk** [comment]
@jaysaikia  Good find! I will investigate this issue and add the event! 

If you could provide a reproduction or explanation with code of the issue that would help me out.

**Comment by jaysaikia** [comment]
Whipped up a quick StackBlitz. Should be self explanatory. Let me know. Hope this helps.
https://stackblitz.com/edit/angular-sbu3ty

**Comment by jaysaikia** [comment]
Will it be better to have just a onload event emitter, which gets fired when the first image is loaded. Dev can get the slideIndex after that event.

And then any subsequent additions of image fires a indexChange event.

**Comment by TSGames** [comment]
May the current index can simply be set using a two-way variable binding?

**Comment by jaysaikia** [comment]
Closing issue, Stackblitz updated and is working as expected ...
