### ISSUE TITLE
Change background-size to contain over cover

### ISSUE THREAD

**Issue by Warriormuffin** [dockleryxk/ng-simple-slideshow#6]
I can't seem to be able to target your slideshow with my own css properties. I would like to change the default background-size from cover to contain.

**Comment by dockleryxk** [comment]
@Warriormuffin I can add this as an input binding. While I am at it, I am going to add background-position and background-repeat as optional inputs as well. Would any other background properties be useful?

**Comment by Warriormuffin** [comment]
Thanks a ton for getting back to me. For me, I really only need the contain option but the more options the better!

**Comment by dockleryxk** [comment]
@Warriormuffin should be good to go now with v1.1.0
