### ISSUE TITLE
Page reloads if the images are still loading

### ISSUE THREAD

**Issue by sergiusxp** [dockleryxk/ng-simple-slideshow#61]
Hi. I have this problem. If the images in the carousel are not loaded yet and I click on the spinning loading gif the page reloads.
I think the problem is in this line
`else if (currentSlide && !isNullOrUndefined(currentSlide.image.href)) {
            this.document.location.href = currentSlide.image.href;
        }`

because the component doesn't check if currentSlide.image.href is empty.

Thanks,

Sergio

**Comment by dockleryxk** [comment]
Great find! I have a fix for this in mind. I will look at this by the end of the week.

**Comment by dockleryxk** [comment]
This should be fixed in v1.3.0-beta.0
