### ISSUE TITLE
Show remaining number on next previous buttons

### ISSUE THREAD

**Issue by Vatsal-Innovatemr** [dockleryxk/ng-simple-slideshow#62]
Is it possible to show the number on the next previous button on the slideshow?
as attached
![screenshot-localhost-4200-2019 03 28-19-26-11](https://user-images.githubusercontent.com/39255553/55163466-dce9e500-518f-11e9-862b-06b2856f9c84.png)

**Comment by dockleryxk** [comment]
No, this isn't a current feature but I am open to PRs!

**Comment by Vatsal-Innovatemr** [comment]
> No, this isn't a current feature but I am open to PRs!

Thanks for the quick response.
