### ISSUE TITLE
Slideshow not showing on route change

### ISSUE THREAD

**Issue by YoniTlz** [dockleryxk/ng-simple-slideshow#65]
Hi,

The slideshow works perfectly fine when accessing my homepage. 

However if you try to access a specific page via URL on your FIRST ACCESS, and then going to the homepage, the slideshow doesn't show.

You can reproduce this when clearing your chache and accessing a component page via URL.
Going back to the homepage produces the exposed effects.

Any lead?

I will soon provide a URL for people to reproduce.

**Comment by dockleryxk** [comment]
@YoniTlz I have never experienced anything remotely similar to this. I also am not sure what the cache has to do with anything. It must be how you are implementing. I will be looking out for that URL

**Comment by YoniTlz** [comment]
It's almost like the component isn't loaded if i'm not accessing my homepage first. I'll provide the URL when the app is up. Thanks.

**Comment by dockleryxk** [comment]
For now, I will close this, but will still be looking out for the URL. To me it sounds like you are only loading the necessary data when entering from the home page, and not otherwise.

If it does happen to be on my end, I will reopen and investigate.
