### ISSUE TITLE
Slideshow not showing on route change #2

### ISSUE THREAD

**Issue by YoniTlz** [dockleryxk/ng-simple-slideshow#66]
Hi,

here's the URL to the site i've been working on:
http://belmaquillagepermanent.fr

When accessing from this URL, the slideshow on the homepage works fine.
However if you FIRST access it from another page such as: http://belmaquillagepermanent.fr/yeux
and navigate back to the homepage the through the "Accueil" link in the navbar, the slideshow will not be displayed.

Do you have any idea how to fix this behavior?

Regards.

**Comment by dockleryxk** [comment]
Could you give me some more detail on how and when you are creating the imageUrls array?

On a side note, the site is super fast and I love the slideshow implementation!

**Comment by YoniTlz** [comment]
So,

In my homepage component i initialize an image array:
HomeComponent: 
`export class HomeComponent implements OnInit {
  @ViewChild('slideshow') slideshow: any;
  imagesPc: (string | any)[] = [
    {
      url: 'assets/images/desktop/banners/bel_banner.jpeg',
      caption: 'caption'
    },
.
.
.`

and directlty reference it in my template.

However for mobile comptatibility purposes, i had to build two of those because the background image wouldn't show properly so i have 2 slideshows but only one rendered depending on the size of the screen:

HomeComponent HTML
`<slideshow
  class="d-none d-md-block"
  [autoPlay]="true"
  [autoPlayInterval]="5000"
  [showArrows]="true"
  [imageUrls]="imagesPc"
  [lazyLoad]="false"
  [autoPlayWaitForLazyLoad]="true"
  [stopAutoPlayOnSlide]="true"
  [arrowSize]="'30px'"
  [showDots]="true"
  [arrowSize]="'30px'"
>
</slideshow>

<slideshow
  class="slide-mobile d-md-none"
  [height]="'300px'"
  [autoPlay]="true"
  [autoPlayInterval]="5000"
  [showArrows]="true"
  [imageUrls]="imagesMobile"
  [lazyLoad]="false"
  [autoPlayWaitForLazyLoad]="true"
  [stopAutoPlayOnSlide]="true"
  [arrowSize]="'30px'"
  [showDots]="true"
  [arrowSize]="'30px'"
>
</slideshow>`

**Comment by dockleryxk** [comment]
Could you send the styles too? I think I could help you only need one slideshow. Also, try setting the array in ngOnInit, and originally initialize it to ```[]```

**Comment by dockleryxk** [comment]
also, add the class d-block to the second slideshow and make sure to give them either a height or a minHeight

**Comment by YoniTlz** [comment]
Here's the CSS i use:

`// Diapo général
/deep/ .slides {
  height: 100%;
  .caption {
    width: 40% !important;
    height: 100% !important;
    display: flex;
    flex-direction: column;
    justify-content: center;
    background-color: transparent !important;
    text-align: center;
    .logo {
      height: 50%;
      img {
        height: 100%;
        width: auto;
      }
    }
  }
}

// 1stslide
/deep/
.slideshow-container[_ngcontent-c2]
.slides:first-child
.caption[_ngcontent-c2] {
  margin-left: 60%;
}

// autres slides
/deep/
.slideshow-container[_ngcontent-c2]
.slides:not(:first-child)
.caption[_ngcontent-c2] {
  margin-left: 5%;
}

// Diapo Ecran PC
@media screen and (min-width: 768px) {
  /deep/ .slideshow-container[_ngcontent-c2] {
    min-height: $sizeLg;
    :hover {
      text-decoration: none;
    }
  }
  /deep/ .slides {
    background-attachment: fixed;
    background-position: top;
    background-repeat: no-repeat;
    background-size: cover;
  }
}

// Diapo Ecran mobile
@media screen and (max-width: 768px) {
  .slide-mobile {
    min-height: $diapoSizeSm;
  }

  /deep/
  .slideshow-container[_ngcontent-c2]
  .slides
  .caption[_ngcontent-c2]
  h2 {
    font-size: 1.1rem !important;
  }
}`

**Comment by YoniTlz** [comment]
I tried adding the class and initialize the arrays in my ngOnInit but it doesn't seem to fix the issue.
Also i noticed that on mobile, if i try to recreate the behavior i 've described, the slideshow actually appears but the styles for the captions aren't applied.

The module seems to not be loaded properly if the homepage isn't accessed first.

**Comment by dockleryxk** [comment]
1. You should remove the `[_ngcontent-c2]` from your styles. Angular adds this automatically when generating.
2. height and minHeight are inputs to the slideshow. Have you tried using these?

**Comment by YoniTlz** [comment]
As simple as that! 

I actually had a height attribute set for the mobile slideshow, that's why it showed and not the other one.
Removing `[_ngcontent-c2]` fixed my CSS. 

It works great now thanks for your help.

**Comment by dockleryxk** [comment]
@YoniTlz one last thing: make sure you get either server-side rendering or prerendering at some point. That will maximize the SEO for this website.

Good luck!

**Comment by YoniTlz** [comment]
I've started to look into it but it's not easy to setup , i'll probably implement it later.
Thanks again.
