### ISSUE TITLE
Resize slideshow using CSS

### ISSUE THREAD

**Issue by YoniTlz** [dockleryxk/ng-simple-slideshow#67]
Hi,

What's the best way to resize the slideshow using css?
I've tried to wrap it in a div and sizing the div using css without giving any height to the slideshow.
This results in an exmpty div, nothing is rendered.

I would like to be able to resize it following the device screen size, orientation etc...
What's your advice?

**Comment by dockleryxk** [comment]
Do you care to share your solution, assuming you have one since you closed this issues

**Comment by YoniTlz** [comment]
Sure,

So basically here's what i've done:
1- wrap the slideshow. Add a custom class to identify it (here "mySlideshow")
HTML
`<div class="wrapper">
  <slideshow
    class="mySlideshow d-block"
    [autoPlay]="true"
    [autoPlayInterval]="5000"
    [showArrows]="true"
    [imageUrls]="images"
    [lazyLoad]="false"
    [autoPlayWaitForLazyLoad]="true"
    [stopAutoPlayOnSlide]="true"
    [arrowSize]="'30px'"
    [showDots]="true"
    [arrowSize]="'30px'"
  >
  </slideshow>
</div>`

2- Give a size to the wrapper in `vh` depending on the size of the screen, orientation etc... through `@media` and use the `mySLideshow` class to specify that the slideshow should fill 100% of its parent height.

CSS:
`@media screen and (min-width: 900px) and (max-width: 1200px) and (min-height: 700px) and (orientation: landscape) {
  .wrapper {
    min-height: 60vh;
    height: 60vh;
    /deep/ .mySlideshow {
      height: 100%;
      min-height: 100%;
    }
  }
}`

That's about it.

**Comment by dockleryxk** [comment]
Nice, thanks!
