### ISSUE TITLE
problems when debug

### ISSUE THREAD

**Issue by malemanw** [dockleryxk/ng-simple-slideshow#72]
I have executed the npm i -S ng-simple-slideshow and I have added it to app.module.ts but when in my HTML I place <slideshow [imageUrls] = "imageUrlArray"> </ slideshow> does not execute the images

**Comment by dockleryxk** [comment]
what is your imageUrlArray variable?

**Comment by malemanw** [comment]
I will try to explain .. when I made the npm I did not install the modules / IImage interface, but import it in import {IImage} from 'node_modules / ng-simple-slideshow / src / app / modules / slideshow / IImage'; and when I call the interface with imageUrls: (string | IImage) [] = [
    {url: 'https://cdn.vox-cdn.com/uploads/chorus_image/image/56748793/dbohn_170625_1801_0018.0.0.jpg', caption: 'The first slide', href: '#config'}
  ]; does not load the image

**Comment by malemanw** [comment]
I'm not at sea because I'm using angular 8.0.3 and it's not yet compatible

**Comment by dockleryxk** [comment]
try using 1.3.0-beta.1
