### ISSUE TITLE
Access slideshow template or nativeElement?

### ISSUE THREAD

**Issue by kerbrose** [dockleryxk/ng-simple-slideshow#74]
Hello There
First thanks for such cool component. I would like to access the rendered html of the slideshow and I couldn't. I tried to use
`
@ViewChild('slideshow') slideshow : any;
this.slideshow.nativeElement;
`
However I get undefined

**Comment by dockleryxk** [comment]
slideshow doesn't have a nativeElement on its type. For this you would need to inject the document and use `this.document.getElementsByClassName('slideshow-container')[0]` to access.

**Comment by kerbrose** [comment]
thank you alot. Also I figured out that I could get from 
`
this.slideshow.container.nativeElement;
`

**Comment by dockleryxk** [comment]
Nice! I didn't even think of that
