### ISSUE TITLE
Binding imageUrls does not update slideshow properly

### ISSUE THREAD

**Issue by esensar** [dockleryxk/ng-simple-slideshow#8]
**Example**
If slideshow is added to html as following: 
```html
<slideshow [imageUrls]="model.imgLinks"></slideshow>
```
and imgLinks in model is modified as following
```ts
this.model.imgLinks.push(url);
```
changes are noticed, but new image is not added to slideshow. If imgLinks are modified as following
```ts
this.model.imgLinks.push(result.url);
const oldArray = this.model.imgLinks;

// Creating a new array
// because of a bug in library
// where array reference is compared, instead of actual array contents
this.model.imgLinks = [];
for (const item of oldArray) {
  this.model.imgLinks.push(item);
}
```
slideshow is properly updated.

**Issue**
After checking code of library, it seems that the way `urlCache` works is the issue. It is set to reference of the array passed to component here:
https://github.com/dockleryxk/ng-simple-slideshow/blob/7f205e4147bbed35f9fded6fd24b74aa00a0d2bb/src/app/modules/slideshow/slideshow.component.ts#L55

And comparing only references here, which will be the same in cases when URLs are added as in the first example.
https://github.com/dockleryxk/ng-simple-slideshow/blob/7f205e4147bbed35f9fded6fd24b74aa00a0d2bb/src/app/modules/slideshow/slideshow.component.ts#L173

**Solution**
If actual contents of the array were copied to cache and then compared when array is changed, this would work as expected. I don't know if it make a performance hit, but it seems like a very small operation. If you agree, I can make a PR.

**Comment by dockleryxk** [comment]
@esensar thank you for the detective work here, and good work finding this bug. I will investigate this by the weekend and let you know once I have resolved the issue. 

The original idea of this was to avoid an rxjs dependency, but I might bite the bullet and just make a subscription to the array depending on performance. If it all works out, I can remove this function altogether.

**Comment by AhsanAyaz** [comment]
@dockleryxk I wouldn't suggest including RxJS for the issue at hand. I worked on a simpler and performant solution. Will create the PR now.

**Comment by dockleryxk** [comment]
I am reopening this because I had to revert the PR that @AhsanAyaz made for now due to an issue with the showDots option
