### ISSUE TITLE
Test and extend peer dependency to Angular 8

### ISSUE THREAD

**Issue by dcanning** [dockleryxk/ng-simple-slideshow#88]
```npm WARN ng-simple-slideshow@1.2.9 requires a peer of @angular/core@^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.```

**Comment by dockleryxk** [comment]
This is currently available in the beta. Install that (1.3.0-beta.2) and you should be good. If you have any problems feel free to open another issue! I personally am using the beta in a prod environment so it should be fine!
