### ISSUE TITLE
Allow resizing pictures so that it fits the container

### ISSUE THREAD

**Issue by PeterTianjieWen** [dockleryxk/ng-simple-slideshow#98]
The project I am currently working on has a couple of pictures with different resolutions. I am wondering if there could be a potential feature of auto-resizing the pictures so that they fit inside the container? Or I think there could be a max-width attribute that allow user to define?

Thanks,
Peter

**Comment by dockleryxk** [comment]
The [backgroundSize](https://lmgtfy.com/?q=background-size+css) input is what you need to use.

**Comment by PeterTianjieWen** [comment]
Thank you so much.
